# Generated by Django 4.2.9 on 2024-01-18 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trigger_web_scraping_dou_api', '0004_alter_journaljsonarrayofdou_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetailSingleJournalOfDOU',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('versao_certificada', models.URLField()),
                ('publicado_dou_data', models.DateField()),
                ('edicao_dou_data', models.CharField(max_length=10)),
                ('secao_dou_data', models.CharField(max_length=10)),
                ('orgao_dou_data', models.TextField()),
                ('title', models.CharField(max_length=255)),
                ('paragrafos', models.TextField()),
                ('assina', models.CharField(max_length=255)),
                ('cargo', models.CharField(max_length=255)),
            ],
        ),
    ]
