# Generated by Django 4.2.9 on 2024-01-10 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JsonArrayOFDOU',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pubName', models.CharField(max_length=255)),
                ('urlTitle', models.CharField(max_length=255)),
                ('numberPage', models.IntegerField()),
                ('subTitulo', models.TextField()),
                ('titulo', models.TextField()),
                ('title', models.TextField()),
                ('pubDate', models.DateField()),
                ('content', models.TextField()),
                ('editionNumber', models.IntegerField()),
                ('hierarchyLevelSize', models.IntegerField()),
                ('artType', models.CharField(max_length=255)),
                ('pubOrder', models.CharField(max_length=255)),
                ('hierarchyStr', models.TextField()),
                ('hierarchyList', models.JSONField()),
            ],
        ),
    ]
