# Generated by Django 4.2.9 on 2024-01-12 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trigger_web_scraping_dou_api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='journaljsonarrayofdou',
            name='id',
        ),
        migrations.AlterField(
            model_name='journaljsonarrayofdou',
            name='urlTitle',
            field=models.CharField(max_length=255, primary_key=True, serialize=False, unique=True),
        ),
    ]
