# Generated by Django 4.2.9 on 2024-01-12 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trigger_web_scraping_dou_api', '0002_remove_journaljsonarrayofdou_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='journaljsonarrayofdou',
            name='id',
            field=models.IntegerField(default=1),
        ),
    ]
